server:
  port: 8080
  #context-path: /helloboot

spring:
    datasource:
        db1:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://10.1.1.32:3306/system_center?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useAffectedRows=true
            username: root
            password: ipharmacare
        db2:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://10.1.1.32:3306/system_center?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&useAffectedRows=true
            username: root
            password: ipharmacare
    data:
        elasticsearch:
            cluster-name: sf-application #集群名(默认值: elasticsearch)
            cluster-nodes: 10.1.1.94:9301 #9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口。
            client-transport-sniff: false
            repositories.enabled: true

http:
#最大连接数
    maxTotal: 100
#并发数
    defaultMaxPerRoute: 20
#创建连接的最长时间
    connectTimeout: 1000
#从连接池中获取到连接的最长时间
    connectionRequestTimeout: 500
#数据传输的最长时间
    socketTimeout: 10000
#提交请求前测试连接是否可用
    staleConnectionCheckEnabled: true

redisson:
# redisson lock
    address: redis://127.0.0.1:6379
    password: ipharmacare