server:
    tomcat:
        uri-encoding: UTF-8
spring:
    profiles:
        active: dev
    messages:
        encoding: UTF-8
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true


#pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql